name: Docker Image CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker Image
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: |
          docker build -t my-image:${{ github.sha }} .
